const C={
1:["Mã dự án","Tên dự án","Số hộ","Hạn hoàn thành","Trạng thái"],
2:["Mã dự án","Tên dự án","Chủ đầu tư","Diện tích (m²)","Ngày bắt đầu","Trạng thái"],
3:["Số thửa","Tờ bản đồ","Chủ sử dụng","Diện tích (m²)","Loại đất","Trạng thái"],
4:["Mã hồ sơ","Chủ hộ","CCCD","Địa chỉ","Số nhân khẩu","Trạng thái"],
5:["Mã phiếu","Chủ hộ","Thửa đất","Tổ kiểm đếm","Ngày kiểm đếm","Trạng thái"],
6:["Mã tài sản","Tên tài sản","Chủ sở hữu","Số lượng","Giá trị (đ)","Trạng thái"],
7:["Mã","Nội dung","Đơn vị tính","Đơn giá (đ)","Ngày hiệu lực","Trạng thái"],
8:["Mã phương án","Chủ hộ","Bồi thường đất (đ)","Bồi thường tài sản (đ)","Tổng giá trị (đ)","Trạng thái"],
9:["Mã hồ sơ","Tên phương án","Đơn vị trình","Ngày tiếp nhận","Người xử lý","Trạng thái"],
10:["Mã","Nội dung","Người gửi","Ngày tiếp nhận","Cán bộ xử lý","Trạng thái"],
11:["Mã","Chủ hộ","Số tiền (đ)","Ngày","Hình thức","Trạng thái"],
12:["Mã hồ sơ","Nội dung","Chủ hộ","Ngày lập","Cán bộ phụ trách","Trạng thái"],
13:["Ranh giới dự án","Thửa đất","Hộ dân","Tài sản","Phạm vi thu hồi"],
14:["Mã","Tên","Đơn vị","Vai trò","Ngày tạo","Trạng thái"]};
// D=dashboard L=danh sách F=biểu mẫu M=bản đồ W=quy trình duyệt R=báo cáo S=cấu hình P=ảnh/minh chứng
const G=[
["Dashboard / Tổng quan GPMB","DDDDDDDL","Tổng quan tình hình GPMB|Thống kê dự án|Thống kê diện tích thu hồi|Thống kê số hộ bị ảnh hưởng|Thống kê phương án bồi thường|Thống kê chi trả|Theo dõi tiến độ GPMB|Cảnh báo hồ sơ chậm tiến độ"],
["Quản lý dự án GPMB","LFMFLLDLL","Danh sách dự án|Thông tin dự án|Phạm vi GPMB|Kế hoạch GPMB|Kế hoạch thu hồi đất|Phân kỳ/khu vực GPMB|Theo dõi tiến độ dự án|Quản lý đơn vị tham gia|Quản lý văn bản dự án"],
["Quản lý đất đai & khu vực thu hồi","LMRLLLRR","Quản lý thửa đất|Xác định phạm vi thu hồi|Diện tích thu hồi|Loại đất|Nguồn gốc sử dụng đất|Tình trạng pháp lý đất|Đối chiếu thông tin đất đai|Tra cứu lịch sử biến động"],
["Quản lý chủ hộ / đối tượng bị ảnh hưởng","LFLFLLLR","Danh sách chủ hộ|Hồ sơ hộ dân|Thành viên hộ|Thông tin liên hệ|Thông tin quyền sử dụng đất|Phân loại đối tượng|Tình trạng ảnh hưởng|Lịch sử xử lý hồ sơ"],
["Quản lý kiểm đếm & xác minh","LFFFFFPWLW","Lập kế hoạch kiểm đếm|Phiếu kiểm đếm|Kiểm đếm đất|Kiểm đếm nhà/công trình|Kiểm đếm cây trồng|Kiểm đếm vật kiến trúc|Chụp ảnh/minh chứng hiện trạng|Xác minh hồ sơ pháp lý|Biên bản kiểm đếm|Phê duyệt/xác nhận kết quả kiểm đếm"],
["Quản lý tài sản bị ảnh hưởng","LLLLLLLFL","Danh mục tài sản|Phân loại tài sản|Nhà ở/công trình|Cây trồng|Vật kiến trúc|Tài sản khác|Đơn giá tài sản|Tính giá trị tài sản|Cập nhật/điều chỉnh tài sản"],
["Quản lý giá & đơn giá bồi thường","LLLLLLLLR","Quản lý bảng giá đất|Giá đất cụ thể|Đơn giá tài sản|Đơn giá cây trồng|Đơn giá công trình/vật kiến trúc|Hệ số điều chỉnh giá|Quản lý chính sách hỗ trợ|Quản lý phiên bản đơn giá|Tra cứu lịch sử áp dụng"],
["Quản lý phương án bồi thường, hỗ trợ, tái định cư","FFFFLLFDFR","Lập phương án|Tính bồi thường đất|Tính bồi thường tài sản|Tính các khoản hỗ trợ|Hỗ trợ ổn định đời sống|Hỗ trợ chuyển đổi nghề|Tính toán tái định cư|Tổng hợp giá trị phương án|Điều chỉnh phương án|In/xuất phương án"],
["Thẩm định & phê duyệt phương án","LWWFFWWL","Tiếp nhận hồ sơ|Kiểm tra hồ sơ|Thẩm định phương án|Ghi nhận ý kiến thẩm định|Yêu cầu bổ sung/chỉnh sửa|Trình phê duyệt|Phê duyệt phương án|Theo dõi trạng thái phê duyệt"],
["Công khai, kiến nghị & khiếu nại","LLFFLWLR","Công khai phương án|Quản lý thời gian công khai|Thông báo cho người dân|Tiếp nhận ý kiến/kiến nghị|Phân loại kiến nghị|Xử lý kiến nghị|Quản lý khiếu nại|Theo dõi kết quả giải quyết"],
["Chi trả, tái định cư & bàn giao mặt bằng","FLDFLFWWL","Lập kế hoạch chi trả|Danh sách chi trả|Theo dõi tình trạng chi trả|Xác nhận nhận tiền|Quản lý tái định cư|Bố trí nền đất/căn hộ|Bàn giao tái định cư|Bàn giao mặt bằng sạch|Biên bản bàn giao"],
["Cưỡng chế, hồ sơ & báo cáo","LLLFLLLRRR","Quản lý trường hợp cưỡng chế|Theo dõi vận động/thuyết phục|Hồ sơ cưỡng chế|Quyết định cưỡng chế|Theo dõi thực hiện cưỡng chế|Quản lý hồ sơ GPMB|Lưu trữ tài liệu điện tử|Báo cáo tổng hợp|Báo cáo tiến độ|Báo cáo bồi thường/chi trả"],
["Bản đồ số GIS","MMMMMMMMMM","Bản đồ tổng thể GPMB|Hiển thị ranh giới dự án|Hiển thị thửa đất|Hiển thị hộ dân|Hiển thị tài sản|Hiển thị phạm vi thu hồi|Tra cứu thông tin trên bản đồ|Chồng lớp dữ liệu GIS|Đo đạc diện tích/khoảng cách|Liên kết đối tượng bản đồ với hồ sơ"],
["Quản trị hệ thống & người dùng","LLSSLLRSWS","Quản lý người dùng|Quản lý vai trò|Phân quyền theo chức năng|Phân quyền theo địa bàn/cấp quản lý|Quản lý đơn vị|Danh mục dùng chung|Nhật ký thao tác|Quản lý cấu hình hệ thống|Quản lý quy trình/workflow|Sao lưu và phục hồi dữ liệu"]
];
[3,4,5,6,7,8,9,10,11,12].forEach(g=>C[g].splice(1,0,"Cảng hàng không"));
const IM={hero:"assets/hero.jpg",crew:"assets/crew.jpg",a1:"assets/apt1.jpg",a2:"assets/apt2.jpg",a3:"assets/apt3.jpg",a4:"assets/apt4.jpg",a5:"assets/apt5.jpg",a6:"assets/apt6.jpg"};
// [mã, cảng, tỉnh/tp, miền, hạng mục, ha, hộ, tỷ đồng, tiến độ %, trạng thái 0=đúng 1=chậm 2=hoàn tất]
const AIR=[["LTH","Long Thành","Đồng Nai","N","Cảng HKQT giai đoạn 1",5000,4730,22800,100,2],["SGN","Tân Sơn Nhất","TP.HCM","N","Nhà ga T3",21,310,4100,64,1],["HAN","Nội Bài","Hà Nội","B","Nhà ga T3 và đường lăn",150,820,5200,78,0],["DAD","Đà Nẵng","Đà Nẵng","T","Nhà ga T3",35,260,3400,85,0],["CXR","Cam Ranh","Khánh Hòa","T","Mở rộng sân đỗ",48,120,900,100,2],["PQC","Phú Quốc","Kiên Giang","N","Mở rộng đường CHC",120,540,3100,71,0],["HUI","Phú Bài","Huế","T","Nhà ga hành khách mới",60,380,1800,55,1],["DLI","Liên Khương","Lâm Đồng","T","Mở rộng sân bay",90,420,1500,88,0],["VII","Vinh","Nghệ An","T","Mở rộng nhà ga",45,300,1200,47,0],["HPH","Cát Bi","Hải Phòng","B","Đường CHC thứ hai",75,350,2300,82,0],["VCA","Cần Thơ","Cần Thơ","N","Mở rộng nhà ga",30,190,800,90,0],["VDO","Vân Đồn","Quảng Ninh","B","Mở rộng sân đỗ",55,150,1100,73,0],["THD","Thọ Xuân","Thanh Hóa","T","Nhà ga T2",40,260,950,52,1],["VCL","Chu Lai","Quảng Nam","T","Nâng cấp khu bay",110,480,1700,66,0],["BMV","Buôn Ma Thuột","Đắk Lắk","T","Mở rộng nhà ga",38,210,700,79,0],["PXU","Pleiku","Gia Lai","T","Nâng cấp đường CHC",42,230,820,58,1]];
const PH=[["a1","Phối cảnh khu nhà ga hành khách","Mẫu"],["a3","Nhà ga và sân đỗ tàu bay","VDO"],["a4","Phối cảnh cụm nhà ga và đường lăn","Mẫu"],["a2","Sân đỗ tàu bay – phối cảnh","Mẫu"],["a5","Quy hoạch tổng thể cảng hàng không","SGN"],["a6","Mô hình 3D khu bay và khu phụ trợ","SGN"]];
const ACT=[["Phê duyệt phương án bồi thường đợt 3","LTH","10 phút trước"],["Hoàn tất kiểm đếm 48 hộ dân","HAN","1 giờ trước"],["Chi trả 12,4 tỷ đồng cho 36 hộ","PQC","3 giờ trước"],["Tiếp nhận 5 kiến nghị mới","SGN","Hôm qua"],["Bàn giao 3,2 ha mặt bằng sạch","DAD","Hôm qua"],["Ban hành quyết định thu hồi đất","HUI","2 ngày trước"]];
const AL=[["Hồ sơ HUI-26-214 quá hạn 12 ngày","HUI"],["Phương án đợt 2 chờ thẩm định hơn 7 ngày","SGN"],["18 hộ chưa nhận tiền bồi thường","THD"],["Chậm bàn giao mặt bằng khu nhà ga","PXU"]];
const GD=["Cung cấp giao diện tổng quan, thống kê và theo dõi tình hình thực hiện GPMB.", "Quản lý thông tin, phạm vi, kế hoạch, tiến độ và hồ sơ của các dự án GPMB.", "Quản lý thông tin thửa đất, phạm vi và hiện trạng pháp lý phục vụ thu hồi đất.", "Quản lý thông tin hộ dân, cá nhân, tổ chức và các đối tượng bị ảnh hưởng bởi thu hồi đất.", "Hỗ trợ kiểm đếm hiện trạng, thu thập minh chứng và xác minh hồ sơ phục vụ lập phương án.", "Quản lý các loại tài sản trên đất và giá trị tài sản bị ảnh hưởng.", "Quản lý các bảng giá, đơn giá và hệ số phục vụ tính toán bồi thường, hỗ trợ.", "Lập, tính toán, tổng hợp và điều chỉnh phương án bồi thường, hỗ trợ, tái định cư.", "Quản lý quy trình kiểm tra, thẩm định, trình và phê duyệt phương án.", "Quản lý công khai phương án, tiếp nhận và xử lý ý kiến, kiến nghị, khiếu nại.", "Theo dõi chi trả, bố trí tái định cư và bàn giao mặt bằng sạch.", "Quản lý các trường hợp cưỡng chế, hồ sơ GPMB và báo cáo kết quả thực hiện.", "Hiển thị và khai thác dữ liệu GPMB trên nền bản đồ số, liên kết đối tượng không gian với hồ sơ.", "Quản lý tài khoản, vai trò, phân quyền, cấu hình và nhật ký vận hành hệ thống."];
const TY={D:"Thống kê và biểu đồ",L:"Danh sách, tìm kiếm, thêm mới",F:"Nhập liệu và cập nhật",M:"Bản đồ và lớp dữ liệu",W:"Quy trình xử lý, phê duyệt",R:"Báo cáo và xuất dữ liệu",S:"Cấu hình hệ thống",P:"Ảnh và minh chứng"};
const NM=["Nguyễn Văn An","Trần Thị Bình","Lê Hoàng Cường","Phạm Thị Dung","Võ Minh Đức","Đặng Thu Hà","Bùi Quốc Huy","Hồ Thị Lan","Ngô Thanh Sơn","Đỗ Thị Mai","Phan Văn Khoa","Vũ Ngọc Ánh","Dương Quang Hải","Lý Thị Hoa","Trịnh Công Minh","Đinh Thị Nga","Huỳnh Văn Tài","Mai Xuân Trường","Cao Thị Yến","Lâm Quốc Bảo"],
PL=["Xã Bình Sơn, H. Long Thành","P. Tân Sơn Nhất, Q. Tân Bình","Xã Phú Minh, H. Sóc Sơn","P. Hòa Thuận, Q. Hải Châu","Xã Cam Hải Đông, Cam Lâm","Xã Dương Tơ, Phú Quốc","P. Thủy Vân, TP. Huế","Xã Hiệp Thạnh, Đức Trọng"],
PJ=AIR.map(a=>a[4]+" "+a[1]),
ST=["Đang xử lý","Hoàn thành","Chờ duyệt","Quá hạn"],SC=["s2","s1","s0","s3"];
const $=s=>document.querySelector(s),fm=n=>n.toLocaleString("vi-VN");
function cell(c,i,g){const h=(i*7+c.length*3+g)%97;
 if(/^Cảng hàng không/.test(c)){const a=AIR[(i*3+h)%AIR.length];return a[0]+" – "+a[1]}
 if(/Chủ đầu/.test(c))return["ACV","Cục Hàng không VN","Vietnam Airlines","Sở GTVT"][(i+h)%4];
 if(/Thửa/.test(c))return"Thửa "+(1+h%90);
 if(/Tổ kiểm/.test(c))return"Tổ "+(1+h%6);
 if(/Tên tài sản/.test(c))return["Nhà cấp 4","Cây cao su","Nhà xưởng","Ao nuôi cá","Cây ăn quả","Hàng rào","Giếng khoan","Chuồng trại"][(i+h)%8];
 if(/Đơn vị tính/.test(c))return["m²","cây","m³"][(i+h)%3];
 if(/Đơn vị/.test(c))return["Ban QLDA ACV","Sở TN&MT","UBND huyện","Hội đồng GPMB"][(i+h)%4];
 if(/^Mã/.test(c))return AIR[(i+h)%AIR.length][0]+"-26-"+String(100+i*13+h).slice(-3);
 if(/Trạng thái/.test(c)){const k=(i+g)%4;return`<span class="b ${SC[k]}">${ST[k]}</span>`}
 if(/^Mã|^Số thửa/.test(c))return`${g<10?"0"+g:g}-${String(1000+i*13+h).slice(-4)}`;
 if(/Tờ/.test(c))return 10+h%30;
 if(/Ngày|Hạn/.test(c))return`${1+h%28}/${1+h%12}/2026`;
 if(/\(đ\)/.test(c))return fm((h+5)*1250000);
 if(/m²/.test(c))return fm(120+h*37);
 if(/Số (hộ|lượng|nhân)/.test(c))return 1+h%40;
 if(/Chủ|Người|Cán bộ|Tên$|CCCD/.test(c))return/CCCD/.test(c)?"079"+String(1e8+h*9973).slice(0,9):NM[(i+h)%8];
 if(/Địa chỉ/.test(c))return PL[(i+h)%4];
 if(/dự án|Chủ đầu/.test(c))return PJ[(i+h)%PJ.length];
 if(/Loại đất/.test(c))return["Đất ở","Đất nông nghiệp","Đất vườn","Đất kinh doanh"][(i+h)%4];
 if(/Vai trò/.test(c))return["Quản trị","Cán bộ GPMB","Thẩm định","Lãnh đạo"][(i+h)%4];
 if(/Hình thức/.test(c))return["Chuyển khoản","Tiền mặt"][i%2];
 return PJ[(i+h)%PJ.length]}
const tbl=(cols,n,g)=>`<div class="tw"><table><tr>${cols.map(c=>`<th>${c}</th>`).join("")}<th></th></tr>${Array.from({length:n},(_,i)=>`<tr>${cols.map(c=>`<td>${cell(c,i,g)}</td>`).join("")}<td><button onclick="modal(0)">Xem</button></td></tr>`).join("")}</table></div>`;
const form=(cols,g)=>`<div class="card"><div class="f">${cols.filter(c=>!/^Mã|Trạng thái/.test(c)).map(c=>`<label>${c}<input value="${String(cell(c,1,g)).replace(/<[^>]+>/g,"")}"></label>`).join("")}<label>Trạng thái<select>${ST.map(s=>`<option>${s}</option>`)}</select></label><label style="grid-column:1/-1">Ghi chú<input placeholder="Nhập ghi chú…"></label></div><div style="margin-top:14px;display:flex;gap:8px"><button class="p" onclick="toast('Đã lưu');closeM()">Lưu</button><button onclick="toast('Đã hủy thay đổi');closeM()">Hủy</button></div></div>`;
function render(g,i,t){const cols=C[g],n=t+1;let h="";
 if("DLRWS".includes(t)||1){}
 if(t=="D")h=dash(g,i);
 else if(t=="L"||t=="R")h=`<div class="k3">${[["Tổng số bản ghi",126],["Đang xử lý",38],["Quá hạn",7]].map(x=>`<div class="card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("")}</div><div class="bar">${t=="R"?`<input type="date"><input type="date"><select><option>Tất cả cảng hàng không</option>${AIR.map(a=>`<option>${a[0]} – ${a[1]}</option>`)}</select><button onclick="toast('Đã áp dụng bộ lọc')">Lọc</button>`:`<input id="sq" oninput="flt()" placeholder="Tìm theo mã, tên, cảng hàng không…" style="flex:1;min-width:200px"><select id="sf" onchange="flt()"><option>Tất cả trạng thái</option>${ST.map(s=>`<option>${s}</option>`)}</select>`}</div><div class="card" id="tb" style="padding:0">${tbl(cols,12,g)}</div><small style="color:var(--mu)">Hiển thị 12 / 126 bản ghi</small>`;
 else if(t=="F")h=form(cols,g);
 else if(t=="W"){const s=["Tiếp nhận","Kiểm tra","Thẩm định","Phê duyệt","Hoàn tất"],c=1+(i%3);
  h=`<div class="st">${s.map((x,k)=>`<div class="${k<c?"d":k==c?"n":""}">${x}</div>`).join("")}</div><div class="card" style="padding:0">${tbl(cols,5,g)}</div><div style="display:flex;gap:8px"><button class="p" onclick="toast('Đã chuyển bước tiếp theo')">Duyệt</button><button onclick="toast('Đã trả lại hồ sơ')">Trả lại</button></div>`}
 else if(t=="S")h=`<div class="card">${["Bật chức năng này","Yêu cầu xác nhận 2 bước","Ghi nhật ký thao tác","Gửi thông báo qua email"].map((x,k)=>`<div class="tg"><span>${x}</span><input type="checkbox" ${k%3?"checked":""}></div>`).join("")}<div style="margin-top:14px"><button class="p" onclick="toast('Đã lưu cấu hình')">Lưu cấu hình</button></div></div>`;
 else if(t=="P")h=`<div class="bar"><button class="p" onclick="toast('Chọn ảnh để tải lên')">Tải ảnh lên</button><button onclick="toast('Mở camera')">Chụp ảnh</button><select><option>Tất cả cảng hàng không</option>${AIR.map(a=>`<option>${a[0]} – ${a[1]}</option>`)}</select></div><div class="pg2">${PH.map((p,k)=>`<figure><img src="${IM[p[0]]}" alt=""><figcaption><b>${p[1]}</b><span>${p[2]} · ${1+k*3}/9/2026 · Tổ kiểm đếm ${1+k%4}</span></figcaption></figure>`).join("")}</div>`;
 else{const L=C[13],sel=g==13&&i>1&&i<7?[i-2]:g==13?[0,1,2,3,4]:[0,1,2];
  h=`<div class="mp"><div class="mapbox"><img id="mi" src="${IM.a5}" alt=""><svg id="sv" viewBox="0 0 639 460"><g id="l0"><polygon points="62,215 300,18 415,40 478,188 612,258 560,335 410,338 335,432 292,420 200,305 62,262" fill="none" stroke="#d99e09" stroke-width="3" stroke-dasharray="9 5"/></g><g id="l1" fill="#ffe08a" fill-opacity=".6" stroke="#b8860b">${[[300,340],[345,352],[388,345],[150,300],[105,282],[440,280],[490,262]].map(p=>`<rect x="${p[0]}" y="${p[1]}" width="40" height="28"/>`).join("")}</g><g id="l2" fill="#005e80" stroke="#fff">${[[318,395],[360,405],[402,392],[170,330],[125,312],[455,315],[505,296],[335,380],[380,380],[420,372]].map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="5"/>`).join("")}</g><g id="l3" fill="#b3382c" stroke="#fff">${[[310,350],[356,362],[398,358],[160,308],[452,290]].map(p=>`<rect x="${p[0]}" y="${p[1]}" width="9" height="9"/>`).join("")}</g><g id="l4"><polygon points="292,330 470,300 520,340 420,350 340,432 300,420" fill="#b3382c" fill-opacity=".3" stroke="#b3382c" stroke-width="2"/></g></svg><div class="mt"><button class="p" onclick="mv(0)">Bản đồ quy hoạch</button><button onclick="mv(1)">Mô hình 3D</button></div></div><div class="ly card"><b>Lớp dữ liệu</b>${L.map((x,k)=>`<label><input type="checkbox" ${sel.includes(k)?"checked":""} onchange="document.getElementById('l${k}').style.display=this.checked?'':'none'">${x}</label>`).join("")}<hr style="border:0;border-top:1px solid var(--bd)"><button onclick="toast('Đo khoảng cách: 1.284 m')">Đo khoảng cách</button> <button onclick="toast('Đo diện tích: 21,4 ha')" style="margin-top:6px">Đo diện tích</button><p style="color:var(--mu);font-size:12px">Nền: quy hoạch tổng thể Tân Sơn Nhất (mô phỏng). Nhấn vào đối tượng để xem hồ sơ liên kết.</p></div></div>`;
  setTimeout(()=>L.forEach((x,k)=>{document.getElementById("l"+k).style.display=sel.includes(k)?"":"none"}),0)}
 return h}
const A={L:"Thêm mới",R:"Xuất Excel",D:"Làm mới"};
let CUR={},LAST="home";
const lk=(id,t)=>`<a href="#${id}" onclick="go('${id}');return false">${t}</a>`;
function hd(t,h,a){$("#ht").textContent=t;$("#hs").innerHTML=h;$("#ha").innerHTML=a||""}
function modal(k){$("#md").innerHTML=`<div class="mx"><div class="mh"><b>${k?"Thêm mới":"Chi tiết"}: ${CUR.nm}</b><button onclick="closeM()">✕</button></div>${form(C[CUR.g],CUR.g)}</div>`;$("#md").style.display="flex"}
function closeM(){$("#md").style.display="none"}
function home(){hd("Trang chủ","Tổng quan hệ thống quản lý giải phóng mặt bằng");
 $("#c").innerHTML=`<div class="card hero"><img src="${IM.hero}" alt=""><div><span class="bg">DEMO</span><h3>Giải phóng mặt bằng các dự án cảng hàng không</h3><p>Theo dõi thu hồi đất, kiểm đếm, bồi thường và bàn giao mặt bằng cho hệ thống sân bay trên toàn quốc.</p><button onclick="go('13.1')">Xem bản đồ GIS</button></div></div>`+KP([["Cảng hàng không đang triển khai",AIR.length],["Hộ bị ảnh hưởng",fm(SM(6))],["Diện tích thu hồi (ha)",fm(SM(5))],["Kinh phí bồi thường (tỷ đồng)",fm(SM(7))]])+`<h4 class="sec">Hình ảnh cảng hàng không</h4><div class="gal">${PH.map(p=>`<div class="gc2" onclick="go('${p[2]=="SGN"?"13.1":"5.7"}')"><img src="${IM[p[0]]}" alt=""><div><b>${p[2]}</b><span>${p[1]}</span></div></div>`).join("")}</div><div id="bd">${board()}</div><div class="two"><div class="card"><b>Hoạt động gần đây</b>${ACT.map(a=>`<div class="ac"><b>${a[1]}</b><span>${a[0]}</span><small>${a[2]}</small></div>`).join("")}</div><div class="card"><b>Cảnh báo cần xử lý</b>${AL.map(a=>`<div class="ac"><b class="w">${a[1]}</b><span>${a[0]}</span></div>`).join("")}</div></div><h4 class="sec">Nhóm chức năng</h4><div class="gr">${G.map((g,k)=>`<div class="card gc" onclick="go('g${k+1}')"><b>${g[0]}</b><p>${GD[k]}</p><small>${g[1].length} chức năng con</small></div>`).join("")}</div>`}
const BN=[IM.a1,IM.a3,IM.a4,IM.a2,IM.crew,IM.a6,IM.hero];
function grp(g){const d=G[g-1];hd(d[0],lk("home","Trang chủ")+" › "+d[0]);
 $("#c").innerHTML=`<div class="bn"><img src="${BN[(g-1)%7]}" alt=""><div><h3>${d[0]}</h3><p>${GD[g-1]}</p></div></div><div class="gr">${d[2].split("|").map((n,j)=>`<div class="card gc" onclick="go('${g}.${j+1}')"><b>${n}</b><p>${TY[d[1][j]]}</p><small>Mở chức năng</small></div>`).join("")}</div>`}
function mark(id){LAST=id;document.querySelectorAll("#menu [data-id]").forEach(a=>a.classList.toggle("on",a.dataset.id==id));if(!$("#q").value)document.querySelectorAll("#menu .g.o").forEach(e=>e.classList.remove("o"));document.querySelectorAll("#menu .on").forEach(e=>e.closest(".g").classList.add("o"))}
function go(id){CUR={};
 if(id=="home")home();else if(id[0]=="g")grp(+id.slice(1));
 else{const[g,i]=id.split(".").map(Number),t=G[g-1][1][i-1],nm=G[g-1][2].split("|")[i-1];CUR={g,i,nm};
  hd(nm,lk("home","Trang chủ")+" › "+lk("g"+g,G[g-1][0])+" › "+nm,A[t]?`<button class="p" onclick="${t=="L"?"modal(1)":`toast('${A[t]}…')`}">${A[t]}</button>`:"");
  $("#c").innerHTML=render(g,i,t)}
 mark(id);closeM();$("#nv").classList.remove("o");$("main").scrollTop=0;try{history.replaceState(null,"","#"+id)}catch(e){}}
const RG={"":"Tất cả",B:"Miền Bắc",T:"Miền Trung – Tây Nguyên",N:"Miền Nam"},SL=["Đúng tiến độ","Chậm tiến độ","Hoàn tất"];
const board=(r="")=>`<div class="fb"><div class="fh"><b>Bảng theo dõi GPMB các cảng hàng không</b><span>${Object.keys(RG).map(k=>`<button class="tb ${k==r?"on":""}" onclick="bf('${k}')">${RG[k]}</button>`).join("")}</span></div><div class="tw"><table><tr><th>Mã</th><th>Cảng hàng không</th><th>Tỉnh/TP</th><th>Hạng mục</th><th>Tiến độ GPMB</th><th>Trạng thái</th></tr>${AIR.filter(a=>!r||a[3]==r).map(a=>`<tr><td class="cd">${a[0]}</td><td>${a[1]}</td><td>${a[2]}</td><td>${a[4]}</td><td><div class="pg"><i style="width:${a[8]}%"></i></div>${a[8]}%</td><td><span class="fs f${a[9]}">${SL[a[9]]}</span></td></tr>`).join("")}</table></div></div>`;
function bf(r){$("#bd").innerHTML=board(r)}
function flt(){const q=$("#sq").value.toLowerCase(),s=$("#sf").value.toLowerCase();[...document.querySelectorAll("#tb tr")].slice(1).forEach(x=>{const t=x.textContent.toLowerCase();x.style.display=(!q||t.includes(q))&&(s.startsWith("tất cả")||t.includes(s))?"":"none"})}
function mv(k){$("#mi").src=k?IM.a6:IM.a5;$("#sv").style.display=k?"none":""}
const SM=k=>AIR.reduce((s,a)=>s+a[k],0),KP=l=>`<div class="k">${l.map(s=>`<div class="card"><span>${s[0]}</span><strong>${s[1]}</strong></div>`).join("")}</div>`;
const MT=[["Tiến độ GPMB (%)",8],["Diện tích thu hồi (ha)",5],["Số hộ bị ảnh hưởng",6],["Kinh phí bồi thường (tỷ đồng)",7]];
function dash(g,i){const m=MT[(g+i)%4],A2=[...AIR].sort((a,b)=>b[m[1]]-a[m[1]]),mx=A2[0][m[1]];
 return KP([["Cảng hàng không",AIR.length],["Diện tích thu hồi (ha)",fm(SM(5))],["Hộ bị ảnh hưởng",fm(SM(6))],["Kinh phí (tỷ đồng)",fm(SM(7))]])+`<div class="card"><b>${m[0]} theo cảng hàng không</b><div class="hb">${A2.map(a=>`<div><span>${a[0]}</span><div class="tr"><i style="width:${a[m[1]]/mx*100}%"></i></div><em>${fm(a[m[1]])}</em></div>`).join("")}</div></div><div class="card"><b>Chi tiết theo cảng hàng không</b><div class="tw"><table><tr>${["Mã","Cảng hàng không","Tỉnh/TP","Hạng mục","Diện tích (ha)","Số hộ","Kinh phí (tỷ)","Tiến độ","Trạng thái"].map(x=>`<th>${x}</th>`).join("")}</tr>${AIR.map(a=>`<tr><td><b>${a[0]}</b></td><td>${a[1]}</td><td>${a[2]}</td><td>${a[4]}</td><td>${fm(a[5])}</td><td>${fm(a[6])}</td><td>${fm(a[7])}</td><td>${a[8]}%</td><td><span class="b s${[2,0,1][a[9]]}">${SL[a[9]]}</span></td></tr>`).join("")}</table></div></div>`}
const IC=['<path d="M3 11l9-8 9 8v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>','<rect x="3" y="3" width="7" height="9"/><rect x="14" y="3" width="7" height="5"/><rect x="14" y="12" width="7" height="9"/><rect x="3" y="16" width="7" height="5"/>','<path d="M22 2 11 13M22 2l-7 20-4-9-9-4z"/>','<path d="M12 21s7-6.2 7-11a7 7 0 1 0-14 0c0 4.8 7 11 7 11z"/><circle cx="12" cy="10" r="2.5"/>','<path d="M17 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2"/><circle cx="10" cy="7" r="4"/><path d="M21 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>','<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2h6v2M9 13l2 2 4-4"/>','<path d="M21 8 12 3 3 8v8l9 5 9-5zM3 8l9 5 9-5M12 13v8"/>','<circle cx="12" cy="12" r="9"/><path d="M15 9.5a3 2 0 0 0-3-1.5c-2 0-3 1-3 2s1 1.7 3 2 3 1 3 2-1 2-3 2a3 2 0 0 1-3-1.5M12 6v2M12 16v2"/>','<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9zM14 3v6h6M8 13h8M8 17h8"/>','<path d="M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6zM9 12l2 2 4-4"/>','<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>','<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20M6 15h4"/>','<path d="M21 8v13H3V8M1 3h22v5H1zM10 12h4"/>','<circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15 15 0 0 1 0 20M12 2a15 15 0 0 0 0 20"/>','<path d="M4 21v-7M4 10V3M12 21v-9M12 8V3M20 21v-5M20 12V3M1 14h6M9 8h6M17 16h6"/>'];
const SN=["Tổng quan","Dự án","Đất đai","Chủ hộ","Kiểm đếm","Tài sản","Đơn giá","Phương án","Phê duyệt","Khiếu nại","Chi trả & TĐC","Cưỡng chế & báo cáo","Bản đồ GIS","Quản trị"];
const ic=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${IC[k]}</svg>`;
function menu(f=""){f=f.toLowerCase();$("#menu").innerHTML=(f?"":`<div class="g"><b data-id="home" onclick="go('home')">${ic(0)}<span>Trang chủ</span></b></div>`)+G.map((g,k)=>{const it=g[2].split("|").map((n,j)=>[`${k+1}.${j+1}`,n]).filter(x=>!f||x[1].toLowerCase().includes(f));return it.length?`<div class="g ${f?"o":""}"><b data-id="g${k+1}" title="${g[0]}" onclick="go('g${k+1}')">${ic(k+1)}<span>${SN[k]}</span><i>›</i></b><div>${it.map(x=>`<a data-id="${x[0]}" title="${x[1]}" href="#${x[0]}" onclick="go('${x[0]}');return false">${x[1]}</a>`).join("")}</div></div>`:""}).join("")}
let tm;function toast(m){const t=$("#t");t.textContent=m;t.style.display="block";clearTimeout(tm);tm=setTimeout(()=>t.style.display="none",1800)}
window.go=go;$("#q").oninput=e=>{menu(e.target.value);mark(LAST)};$("#mb").onclick=()=>$("#nv").classList.toggle("o");
$("#cl").onclick=()=>document.body.classList.toggle("mini");menu();go((location.hash||"#home").slice(1));
